### ISSUE TITLE
traceback in 3126

### ISSUE THREAD

**Issue by ildarkhasanshin** [shagabutdinov/sublime-utilities#1]
reloading plugin SublimeEnhancedUtilitiesSet.commands
Some dependencies has not been imported for Utilities package; some utilities functionality will not be availiable
reloading plugin SublimeEnhancedUtilitiesSet.go
Traceback (most recent call last):
  File "/opt/sublime_text/sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "/opt/sublime_text/sublime_plugin.py", line 915, in load_module
    exec(compile(source, source_path, 'exec'), mod.__dict__)
  File "go in /home/ildar/.config/sublime-text-3/Installed Packages/SublimeEnhancedUtilitiesSet.sublime-package", line 2, in <module>
ImportError: No module named 'Expression'

st 3126
ubuntu 1610

**Comment by shagabutdinov** [comment]
Hi, ildar!

Please, install "Expression" module from my other plugins in order get this
plugin work. Thank you for reporting.

## 

Leonid Shagabutdinov,
+7 905 937 6988
